// 各自治体が独自ポータル/自庁サイトで公開している食品営業許可オープンデータ。
// （BODIK 掲載分は bodik-sources.js、既存4件は sources.js 本体で対応）
//
// 出典・実URL・文字コードは調査時点（2026-07）のもの。年度更新でURLが変わる自治体も
// あり、その場合は当該ソースのみダウンロードに失敗してスキップされる（他は継続）。
// 都道府県のみ指定（defaultCity なし）のソースは、市区町村をジオコーディングで補完する。

export const PORTAL_SOURCES = [
  // ===== 北海道・東北 =====
  { key: 'sapporo', acquire: { type: 'get', url: 'https://ckan.pf-sapporo.jp/dataset/be44af14-f135-41b9-acca-08e215d8a540/resource/54618ac4-da90-493c-8a20-8df29be9d435/download/shokuhin260331.csv', format: 'csv', encoding: 'utf-8' }, source: '札幌市食品営業許可施設一覧', license: 'CC BY 4.0', defaultPref: '北海道', defaultCity: '札幌市' },
  { key: 'aomori-city', acquire: { type: 'get', url: 'https://www.city.aomori.aomori.jp/_res/projects/default_project/_page_/001/006/184/r0805zendate.csv', format: 'csv', encoding: 'utf-8' }, source: '青森市食品営業許可施設一覧', license: 'CC BY 4.0', defaultPref: '青森県', defaultCity: '青森市' },
  { key: 'morioka', acquire: { type: 'get', url: 'https://www.city.morioka.iwate.jp/_res/projects/default_project/_page_/001/006/689/20260630.csv', format: 'csv', encoding: 'utf-8' }, source: '盛岡市食品営業許可施設一覧', license: 'CC BY 4.0', defaultPref: '岩手県', defaultCity: '盛岡市' },
  { key: 'akita-city', acquire: { type: 'get', url: 'https://www.city.akita.lg.jp/_res/projects/default_project/_page_/001/017/339/r080601.xlsx', format: 'xlsx' }, source: '秋田市食品営業許可施設一覧', license: 'CC BY 4.0', defaultPref: '秋田県', defaultCity: '秋田市' },
  { key: 'yamagata-city', acquire: { type: 'get', url: 'https://www.city.yamagata-yamagata.lg.jp/_res/projects/default_project/_page_/001/012/802/062014_syokuhin_list_20260531.csv', format: 'csv', encoding: 'shift_jis' }, source: '山形市食品営業許可・届出施設一覧', license: 'CC BY 4.0', defaultPref: '山形県', defaultCity: '山形市' },
  { key: 'fukushima-pref', acquire: { type: 'get', url: 'https://www.pref.fukushima.lg.jp/uploaded/attachment/743308.xlsx', format: 'xlsx' }, source: '福島県食品営業許可施設一覧', license: 'CC BY 2.1 JP', defaultPref: '福島県' },
  { key: 'fukushima-city', acquire: { type: 'get', url: 'https://www.city.fukushima.fukushima.jp/material/files/group/7/R7nendo_syokuhin.csv', format: 'csv', encoding: 'utf-8' }, source: '福島市食品営業許可施設一覧', license: 'CC BY 2.1 JP', defaultPref: '福島県', defaultCity: '福島市' },
  { key: 'koriyama', acquire: { type: 'get', url: 'https://www.city.koriyama.lg.jp/uploaded/attachment/120902.xls', format: 'xls' }, source: '郡山市食品営業許可施設一覧', license: '要確認', defaultPref: '福島県', defaultCity: '郡山市' },
  { key: 'iwaki', acquire: { type: 'get', url: 'https://www.city.iwaki.lg.jp/www/contents/1652661537484/simple/Shokuhin_itiran_R08.csv', format: 'csv', encoding: 'utf-8' }, source: 'いわき市食品営業許可施設一覧', license: 'CC BY 4.0', defaultPref: '福島県', defaultCity: 'いわき市' },

  // ===== 関東 =====
  { key: 'utsunomiya', acquire: { type: 'get', url: 'https://catalog.city.utsunomiya.tochigi.jp/dataset/4b5cae93-4640-4b4e-87bb-a5e18042366c/resource/a53500f2-7ba1-4e77-a906-e17dc5b60714/download/092011_seikatsueisei_shokuhin_shokuhin.csv', format: 'csv', encoding: 'utf-8' }, source: '宇都宮市食品営業許可施設一覧', license: 'CC BY 4.0', defaultPref: '栃木県', defaultCity: '宇都宮市' },
  { key: 'takasaki', acquire: { type: 'get', url: 'https://www.city.takasaki.gunma.jp/uploaded/attachment/40475.xlsx', format: 'xlsx' }, source: '高崎市食品営業許可施設一覧', license: '要確認', defaultPref: '群馬県', defaultCity: '高崎市' },
  { key: 'kawaguchi', acquire: { type: 'get', url: 'https://www.city.kawaguchi.lg.jp/material/files/group/232/R0803zenshisetsuichiran.xls', format: 'xls' }, source: '川口市食品衛生営業許可施設一覧', license: '要確認', defaultPref: '埼玉県', defaultCity: '川口市' },
  { key: 'chiba-city', acquire: { type: 'get', url: 'https://www.city.chiba.jp/somu/somu/seisakuhomu/shisei/documents/202605syokuhin.xlsx', format: 'xlsx' }, source: '千葉市食品営業許可施設一覧', license: '要確認', defaultPref: '千葉県', defaultCity: '千葉市' },
  { key: 'kashiwa', acquire: { type: 'get', url: 'https://www.city.kashiwa.lg.jp/documents/24912/122173_food_business_all.csv', format: 'csv', encoding: 'auto' }, source: '柏市食品営業許可一覧', license: '柏市オープンデータ利用規約', defaultPref: '千葉県', defaultCity: '柏市' },
  { key: 'chuo-ku', acquire: { type: 'get', url: 'https://www.city.chuo.lg.jp/documents/984/syokuhineigyoukyoka.csv', format: 'csv', encoding: 'shift_jis' }, source: '東京都中央区食品等営業許可・届出一覧', license: 'CC BY 4.0', defaultPref: '東京都', defaultCity: '中央区' },
  { key: 'shinjuku-ku', acquire: { type: 'get', url: 'https://www.city.shinjuku.lg.jp/content/000399975.csv', format: 'csv', encoding: 'utf-16' }, source: '東京都新宿区食品等営業許可・届出一覧', license: 'CC BY 4.0', defaultPref: '東京都', defaultCity: '新宿区' },
  { key: 'taito-ku', acquire: { type: 'get', url: 'https://www.city.taito.lg.jp/kenkohukusi/kenkokikikanrieisei/food/syokuhin-sisetu/index.files/2026ALL-IND-CSV.csv', format: 'csv', encoding: 'shift_jis' }, source: '東京都台東区食品衛生営業施設一覧', license: 'CC BY 4.0', defaultPref: '東京都', defaultCity: '台東区' },
  { key: 'koto-ku', acquire: { type: 'get', url: 'https://www.opendata.metro.tokyo.lg.jp/koto/131083_015_food_business_all.csv', format: 'csv', encoding: 'utf-8' }, source: '東京都江東区食品等営業許可・届出一覧', license: 'CC BY 4.0', defaultPref: '東京都', defaultCity: '江東区' },
  { key: 'shinagawa-ku', acquire: { type: 'get', url: 'https://www.city.shinagawa.tokyo.jp/contentshozon2026/R6-7.csv', format: 'csv', encoding: 'shift_jis' }, source: '東京都品川区食品衛生許可施設', license: 'CC BY 4.0', defaultPref: '東京都', defaultCity: '品川区' },
  { key: 'nakano-ku', acquire: { type: 'get', url: 'https://www2.wagmap.jp/nakanodatamap/nakanodatamap/opendatafile/map_40/CSV/opendata_550150.csv', format: 'csv', encoding: 'utf-8' }, source: '東京都中野区食品等営業許可届出一覧', license: 'CC BY 4.0', defaultPref: '東京都', defaultCity: '中野区' },
  { key: 'setagaya-ku', acquire: { type: 'get', url: 'https://www.city.setagaya.lg.jp/documents/3246/zenkenr080331.csv', format: 'csv', encoding: 'shift_jis' }, source: '東京都世田谷区食品衛生営業許可施設', license: 'CC BY 4.0', defaultPref: '東京都', defaultCity: '世田谷区' },
  { key: 'shibuya-ku', acquire: { type: 'get', url: 'https://city-shibuya-data.opendata.arcgis.com/api/download/v1/items/e68f41ebfa5f4ea490ca9af701d44e02/csv?layers=0', format: 'csv', encoding: 'utf-8' }, source: '東京都渋谷区食品等営業許可・届出一覧', license: 'CC BY 4.0', defaultPref: '東京都', defaultCity: '渋谷区' },
  { key: 'itabashi-ku', acquire: { type: 'get', url: 'https://www.city.itabashi.tokyo.jp/_res/projects/default_project/_page_/001/051/220/r8.5_shokuhinkyokashisetsu.xlsx', format: 'xlsx' }, source: '東京都板橋区食品営業許可施設一覧', license: '要確認', defaultPref: '東京都', defaultCity: '板橋区' },
  { key: 'higashimurayama', acquire: { type: 'get', url: 'https://www.opendata.metro.tokyo.lg.jp/higashimurayama/20240619_food_business_all.csv', format: 'csv', encoding: 'utf-8' }, source: '東京都東村山市食品等営業許可・届出一覧', license: 'CC BY 4.0', defaultPref: '東京都', defaultCity: '東村山市' },
  { key: 'kawasaki', acquire: { type: 'get', url: 'https://www.city.kawasaki.jp/350/cmsfiles/contents/0000093/93741/080503(UTF-8).csv', format: 'csv', encoding: 'utf-8' }, source: '川崎市食品営業許可施設情報', license: 'CC BY 4.0', defaultPref: '神奈川県', defaultCity: '川崎市' },
  { key: 'chigasaki', acquire: { type: 'get', url: 'https://www.city.chigasaki.kanagawa.jp/_res/projects/default_project/_page_/001/041/779/syokuhinall2025.csv', format: 'csv', encoding: 'shift_jis' }, source: '茅ヶ崎市食品営業許可台帳', license: '要確認', defaultPref: '神奈川県', defaultCity: '茅ヶ崎市' },
  { key: 'fujisawa', acquire: { type: 'get', urls: ['https://www.city.fujisawa.kanagawa.jp/documents/28905/zende-ta2020603houjin.csv'], format: 'tsv', encoding: 'utf-16' }, source: '藤沢市食品営業許可施設情報', license: '要確認', defaultPref: '神奈川県', defaultCity: '藤沢市' },

  // ===== 中部 =====
  { key: 'toyama-pref', acquire: { type: 'get', url: 'https://toyama-pref.box.com/shared/static/1t6074lluawpua1u5jhx1yeaynb48rle.csv', format: 'csv', encoding: 'shift_jis' }, source: '富山県食品営業許可施設一覧', license: 'CC BY', defaultPref: '富山県' },
  { key: 'toyama-city', acquire: { type: 'get', url: 'https://opdt.city.toyama.lg.jp/dataset/fb1198c6-3ac2-42fc-ae99-81ea5ba09a2d/resource/fa38003f-accd-4690-b71b-96b1d78e1c45/download/syokuhin.xlsx', format: 'xlsx' }, source: '富山市食品営業許可施設', license: 'CC BY', defaultPref: '富山県', defaultCity: '富山市' },
  { key: 'ishikawa-pref', acquire: { type: 'get', url: 'https://www.pref.ishikawa.lg.jp/yakuji/syokuhin/documents/nendor7.xlsx', format: 'xlsx' }, source: '石川県営業許可施設一覧', license: '石川県利用規約', defaultPref: '石川県' },
  { key: 'kanazawa', acquire: { type: 'get', url: 'https://catalog-data.city.kanazawa.ishikawa.jp/datastore/dump/09a49521-cabf-40b4-978b-bd61ef02f650?bom=true', format: 'csv', encoding: 'utf-8' }, source: '金沢市食品衛生関係営業許可施設一覧', license: 'CC BY', defaultPref: '石川県', defaultCity: '金沢市' },
  { key: 'fukui-pref', acquire: { type: 'get', urls: ['https://data.odp.jig.jp/viewcsv/jp/fukui/776.csv', 'https://data.odp.jig.jp/viewcsv/jp/fukui/777.csv'], format: 'csv', encoding: 'utf-8' }, source: '福井県食品営業許可取得施設', license: 'CC BY', defaultPref: '福井県' },
  { key: 'fukui-city', acquire: { type: 'get', url: 'https://www.city.fukui.lg.jp/fukusi/eisei/syokuhin/p070519_d/fil/11syokuhin_202605.xlsx', format: 'xlsx' }, source: '福井市食品営業許可施設一覧', license: '要確認', defaultPref: '福井県', defaultCity: '福井市' },
  { key: 'yamanashi-pref', acquire: { type: 'get', url: 'https://www.pref.yamanashi.jp/documents/23776/190004_food_business_all.csv', format: 'csv', encoding: 'shift_jis' }, source: '山梨県営業許可施設一覧', license: 'CC BY 2.1 JP', defaultPref: '山梨県' },
  { key: 'nagano-pref', acquire: { type: 'get', url: 'https://www.pref.nagano.lg.jp/shokusei/kenko/shokuhin/seikatsu/documents/food_20260531_csv.csv', format: 'csv', encoding: 'utf-8' }, source: '長野県食品営業許可施設', license: '要確認', defaultPref: '長野県' },
  { key: 'nagano-city', acquire: { type: 'get', url: 'https://www.city.nagano.nagano.jp/documents/1948/202011_food_business_202605.csv', format: 'csv', encoding: 'utf-8' }, source: '長野市食品営業許可施設', license: 'CC BY 4.0', defaultPref: '長野県', defaultCity: '長野市' },
  { key: 'matsumoto', acquire: { type: 'get', url: 'http://linkdata.org/download/rdf1s8748i/link/shokuhin_kyoka_eigyo_matsumoto.txt', format: 'tsv', encoding: 'utf-8' }, source: '松本市食品営業許可台帳', license: 'CC BY 3.0', defaultPref: '長野県', defaultCity: '松本市' },
  { key: 'gifu-pref', acquire: { type: 'get', url: 'https://gifu-opendata.pref.gifu.lg.jp/dataset/f6bbdb66-1d55-4e55-82cb-15fe1bb24223/resource/3c7d862d-a126-4441-a5b1-4839096b2591/download/20250331syokuhin.csv', format: 'csv', encoding: 'utf-8' }, source: '岐阜県食品営業許可施設情報', license: 'CC BY 2.0', defaultPref: '岐阜県' },
  { key: 'gifu-city', acquire: { type: 'get', url: 'https://gifu-opendata.pref.gifu.lg.jp/dataset/2f9f1b1c-be25-4a27-96c6-47b597f1a0bd/resource/16ef7794-d2b6-4d7d-8353-f55193432530/download/gifushisyokuhinkyokar7.6.1.csv', format: 'csv', encoding: 'utf-8' }, source: '岐阜市食品等営業許可一覧', license: 'CC BY 2.0', defaultPref: '岐阜県', defaultCity: '岐阜市' },
  { key: 'hamamatsu', acquire: { type: 'get', url: 'https://static.hamamatsu.odpf.net/opendata/v01/syokuhineiseidaityou202401/syokuhineiseidaityou202401.csv', format: 'csv', encoding: 'shift_jis' }, source: '浜松市食品衛生台帳（新規）', license: 'CC BY', defaultPref: '静岡県', defaultCity: '浜松市' },
  { key: 'aichi-pref', acquire: { type: 'get', url: 'https://www.pref.aichi.jp/uploaded/attachment/619853.csv', format: 'csv', encoding: 'utf-8' }, source: '愛知県食品営業者台帳（新規許可）', license: '要確認', defaultPref: '愛知県' },
  { key: 'toyohashi', acquire: { type: 'get', url: 'https://www.city.toyohashi.lg.jp/secure/18290/shokuhinshinki202605EXCEL.xlsx', format: 'xlsx' }, source: '豊橋市食品営業許可施設情報（新規）', license: '要確認', defaultPref: '愛知県', defaultCity: '豊橋市' },
  { key: 'ichinomiya', acquire: { type: 'get', url: 'https://www.city.ichinomiya.aichi.jp/_res/projects/default_project/_page_/001/040/636/232033_Food_Business_All_20260331.csv', format: 'csv', encoding: 'auto' }, source: '一宮市食品営業許可台帳', license: 'CC BY 4.0', defaultPref: '愛知県', defaultCity: '一宮市' },

  // ===== 近畿 =====
  { key: 'shiga-pref', acquire: { type: 'get', urls: ['https://www.pref.shiga.lg.jp/file/attachment/5615791.csv', 'https://www.pref.shiga.lg.jp/file/attachment/5615790.csv'], format: 'csv', encoding: 'shift_jis' }, source: '滋賀県食品営業許可施設一覧', license: '滋賀県OD利用規約', defaultPref: '滋賀県' },
  { key: 'otsu', acquire: { type: 'get', url: 'https://www.city.otsu.lg.jp/material/files/group/4/od_2605.csv', format: 'csv', encoding: 'utf-8' }, source: '大津市食品営業許可施設一覧', license: '要確認', defaultPref: '滋賀県', defaultCity: '大津市' },
  { key: 'hirakata', acquire: { type: 'get', url: 'https://www.city.hirakata.osaka.jp/cmsfiles/contents/0000023/23479/272108_food_business_all_202603_end.csv', format: 'csv', encoding: 'shift_jis' }, source: '枚方市食品等営業許可施設一覧', license: 'CC BY 2.1 JP', defaultPref: '大阪府', defaultCity: '枚方市' },
  { key: 'suita', acquire: { type: 'get', url: 'https://www.city.suita.osaka.jp/_res/projects/default_project/_page_/001/017/170/20260331new.xlsx', format: 'xlsx' }, source: '吹田市食品営業許可施設一覧', license: 'CC BY 4.0', defaultPref: '大阪府', defaultCity: '吹田市' },
  { key: 'hyogo-pref', acquire: { type: 'get', url: 'https://web.pref.hyogo.lg.jp/kf14/documents/000028_food_business_lisence_all.xlsx', format: 'xlsx' }, source: '兵庫県食品関係営業施設リスト（許可）', license: '要確認', defaultPref: '兵庫県' },
  { key: 'kobe', acquire: { type: 'get', url: 'https://www.city.kobe.lg.jp/documents/6359/20260407150739.csv', format: 'csv', encoding: 'shift_jis' }, source: '神戸市食品営業許可施設一覧', license: 'CC BY 2.1 JP', defaultPref: '兵庫県', defaultCity: '神戸市' },
  { key: 'amagasaki', acquire: { type: 'get', url: 'https://www.city.amagasaki.hyogo.jp/_res/projects/default_project/_page_/001/001/025/kyoka202605.csv', format: 'csv', encoding: 'utf-8' }, source: '尼崎市食品営業許可施設', license: 'CC BY 4.0', defaultPref: '兵庫県', defaultCity: '尼崎市' },
  { key: 'nishinomiya', acquire: { type: 'get', url: 'http://opendata.nishi.or.jp/opendata/files/9/R8.5ichiran_syokuhin.xlsx', format: 'xlsx' }, source: '西宮市食品営業許可施設一覧', license: 'CC BY相当', defaultPref: '兵庫県', defaultCity: '西宮市' },
  { key: 'nara-city', acquire: { type: 'get', url: 'https://www.city.nara.lg.jp/uploaded/attachment/203480.csv', format: 'csv', encoding: 'utf-8' }, source: '奈良市食品営業許可施設', license: 'CC BY 2.1 JP', defaultPref: '奈良県', defaultCity: '奈良市' },

  // ===== 中国・四国 =====
  { key: 'tottori-city', acquire: { type: 'get', url: 'https://odp-pref-tottori.tori-info.co.jp/dataset/1858/resource/9560/312011_food_business_all.csv', format: 'csv', encoding: 'utf-8' }, source: '鳥取市食品等営業許可・届出一覧', license: 'CC BY', defaultPref: '鳥取県', defaultCity: '鳥取市' },
  { key: 'matsue', acquire: { type: 'get', url: 'https://www.city.matsue.lg.jp/material/files/group/50/202605_eigyoukyoka_zenken.xlsx', format: 'xlsx' }, source: '松江市食品営業許可施設一覧', license: '要確認', defaultPref: '島根県', defaultCity: '松江市' },
  { key: 'fukuyama', acquire: { type: 'get', url: 'https://data.city.fukuyama.hiroshima.jp/dataset/61f415c5-88f7-46d0-8ada-4bb8855685a0/resource/21fec913-dc08-4344-94d1-ffb0068ab147/download/2026_3all.csv', format: 'csv', encoding: 'auto' }, source: '福山市営業許認可等施設一覧', license: 'CC BY', defaultPref: '広島県', defaultCity: '福山市' },
  { key: 'yamaguchi-pref', acquire: { type: 'get', url: 'https://yamaguchi-opendata.jp/ckan/dataset/9d0d2325-62b4-447c-8817-a381c968a5cd/resource/44efb857-48c7-4a2e-9e99-61bf38f6f125/download/350001_food_business_all.csv', format: 'csv', encoding: 'utf-8' }, source: '山口県食品営業許可施設情報一覧', license: 'CC BY', defaultPref: '山口県' },
  { key: 'shimonoseki', acquire: { type: 'get', url: 'https://yamaguchi-opendata.jp/ckan/dataset/50c21bfa-4ee1-4553-b166-8ed2e625a6f5/resource/f61a61f9-a9ca-448f-8e48-38f647fd2539/download/352012_food_business_map.csv', format: 'csv', encoding: 'utf-8' }, source: '下関市食品営業許可施設一覧（マップ用）', license: 'CC BY', defaultPref: '山口県', defaultCity: '下関市' },
  { key: 'tokushima-pref', acquire: { type: 'get', url: 'https://opendata.pref.tokushima.lg.jp/dataset/4615/resource/14084/36000_food_business_all.csv', format: 'csv', encoding: 'utf-8' }, source: '徳島県食品等営業許可・届出一覧', license: 'CC BY', defaultPref: '徳島県' },
  { key: 'takamatsu', acquire: { type: 'get', url: 'https://opendata.takamatsu-fact.com/licensed_food_business_facility_list/data.csv', format: 'csv', encoding: 'utf-8' }, source: '高松市食品等営業許可施設一覧', license: 'CC BY', defaultPref: '香川県', defaultCity: '高松市' },
  { key: 'matsuyama', acquire: { type: 'get', urls: ['https://www.city.matsuyama.ehime.jp/shisei/opendata/metadata/shokuhin.files/382019_food_business_all_2026031.csv', 'https://www.city.matsuyama.ehime.jp/shisei/opendata/metadata/shokuhin.files/382019_food_business_all_2026032.csv'], format: 'csv', encoding: 'utf-8' }, source: '松山市食品営業許可全施設一覧', license: 'CC BY', defaultPref: '愛媛県', defaultCity: '松山市' },

  // ===== 九州 =====
  { key: 'kumamoto-city', acquire: { type: 'get', url: 'https://www.city.kumamoto.jp/dynamic/opendata/pub/Insyokutenneigyoukyoka.csv', format: 'csv', encoding: 'utf-8' }, source: '熊本市飲食店営業許可施設一覧', license: '公共データ利用規約', defaultPref: '熊本県', defaultCity: '熊本市' },
  { key: 'oita-city', acquire: { type: 'get', urls: ['https://www.city.oita.oita.jp/o095/kenko/hoken/documents/r080601allkyoka.csv', 'https://www.city.oita.oita.jp/o095/kenko/hoken/documents/r080601alltodoke.csv'], format: 'csv', encoding: 'auto' }, source: '大分市食品営業許可・届出施設一覧', license: 'CC BY 2.1 JP', defaultPref: '大分県', defaultCity: '大分市' },
];
